# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Select Xcode
        run: 
          sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'

      #- name: Run macOS tests
      #  run: 
      #    xcodebuild -workspace Orgel_Mac.xcworkspace -scheme Orgel_Mac_Tests -configuration Debug OBJROOT=build -sdk macosx clean test

      - name: Run iOS tests
        run: 
          xcodebuild -workspace Orgel_iOS.xcworkspace -scheme Orgel_iOS_Tests -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' clean test

      #- name: Run Macro tests
      #  run:
      #    xcodebuild -workspace Orgel_Mac.xcworkspace -scheme OrgelObjectTests -configuration Debug OBJROOT=build -sdk macosx clean test