# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Select Xcode
        run: 
          sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'

      - name: Run Mac tests
        run:
          xcodebuild
            -scheme Orgel
            -configuration debug
            -destination 'platform=macOS'
            clean test

      - name: Run Macro tests
        run:
          xcodebuild
            -scheme OrgelMacrosTests
            -configuration debug
            -destination 'platform=macOS'
            clean test

      - name: Run iOS build
        run:
          xcodebuild
            -scheme Orgel
            -configuration debug
            -destination 'platform=iOS Simulator,name=iPhone 15'
            clean build
